//ONLY ADMIN
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";

// USER

export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_FAIL = "API_CALL_FAIL";
export const UPLOAD_DATA_SUCCESS = "UPLOAD_DATA_SUCCESS";
export const UPLOAD_DATA_FAIL = "UPLOAD_DATA_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const SET_FILE = "SET_FILE";
export const EDIT_DATA_BEGIN = "EDIT_DATA_BEGIN";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
export const EDIT_DATA_FAIL = "EDIT_DATA_FAIL";
export const GET_ALL_EDIT_REQUEST_SUCCESS = "GET_ALL_EDIT_REQUEST_SUCCESS";
export const APPROVE_EDIT_SUCCESS = "APPROVE_EDIT_SUCCESS";
export const REJECT_EDIT_SUCCESS = "REJECT_EDIT_SUCCESS";
("");
